# This file contains configuration that re-enables PsychoPy analysis on
# lgtm.com (see https://lgtm.com/projects/g/psychopy/psychopy)
#
# More details on configuration options:
# https://lgtm.com/docs/lgtm/lgtm-configuration-file

extraction:
  python: 
    prepare: 
      packages: 
        - python-wxtools
        - libgtk-3-dev
        - mesa-common-dev
        - libglu1-mesa-dev
        - libgstreamer1.0-dev
        - libgstreamer-plugins-base1.0-dev
        - libwebkitgtk-3.0-dev
